export const sample_foods = [
    {
      id: '1',
      name: 'Pancakes',
      cookTime: '10-20',
      price: 10,
      favorite: false,
      origins: ['italy'],
      stars: 4.5,
      imageUrl: 'food-1.jpg',
      tags: ['FastFood', 'Pancakes', 'Brunch'],
    },
    {
      id: '2',
      name: 'Subway',
      price: 20,
      cookTime: '10-20',
      favorite: true,
      origins: ['US'],
      stars: 5,
      imageUrl: 'food-2.jpg',
      tags: ['SlowFood', 'Lunch'],
    },
    {
      id: '3',
      name: 'French Fries',
      price: 5,
      cookTime: '10-15',
      favorite: false,
      origins: ['france', 'us'],
      stars: 3.5,
      imageUrl: 'food-3.jpg',
      tags: ['FastFood', 'fries'],
    },
    {
      id: '4',
      name: 'Indian Thali',
      price: 20,
      cookTime: '35-40',
      favorite: true,
      origins: ['India', ],
      stars: 3,
      imageUrl: 'food-4.jpg',
      tags: ['SlowFood', 'indian'],
    },
    {
      id: '5',
      name: 'Momos',
      price: 11,
      cookTime: '40-50',
      favorite: false,
      origins: [ 'middle east', 'china', 'asia'],
      stars: 3.5,
      imageUrl: 'food-5.jpg',
      tags: ['SlowFood', 'dumplings'],
    },
    {
      id: '6',
      name: 'Strawberry Cheesecake',
      price: 9,
      cookTime: '40-50',
      favorite: false,
      origins: ['italy'],
      stars: 4.0,
      imageUrl: 'food-6.jpg',
      tags: ['FastFood', 'cake', 'dessert'],
    },
  ];
  
  export const sample_tags = [
    { name: 'All', count: 6 },
    { name: 'FastFood', count: 4 },
    { name: 'Pizza', count: 2 },
    { name: 'Lunch', count: 3 },
    { name: 'SlowFood', count: 2 },
    { name: 'Hamburger', count: 1 },
    { name: 'Fry', count: 1 },
    { name: 'Soup', count: 1 },
  ];
  
  export const sample_users = [
    {
      id: 1,
      name: 'John Doe',
      email: 'john@gmail.com',
      password: '12345',
      address: 'Toronto On',
      isAdmin: false,
    },
    {
      id: 2,
      name: 'Jane Doe',
      email: 'jane@gmail.com',
      password: '12345',
      address: 'Shanghai',
      isAdmin: true,
    },
  ];